# Generated by Django 2.2.10 on 2021-06-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.IntegerField(choices=[(1, 'Текст'), (2, 'Выбор варианта'), (3, 'Множественный выбор')], default=1),
        ),
    ]
