# Generated by Django 2.2.10 on 2021-06-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0002_auto_20210622_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_begin',
        ),
    ]
