# Generated by Django 2.2.10 on 2021-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0003_remove_poll_date_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_begin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
