# Generated by Django 2.2.10 on 2021-06-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0004_poll_date_begin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='desc',
        ),
    ]
