# Generated by Django 2.2.10 on 2021-06-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0005_auto_20210622_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_begin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='date_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
