# Generated by Django 2.2.10 on 2021-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0007_auto_20210622_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='dfsdf',
            field=models.CharField(default='ff', max_length=10),
        ),
    ]
