# Generated by Django 2.2.10 on 2021-06-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0008_poll_dfsdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='date_begin',
            new_name='dateBegin',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='date_end',
            new_name='dateEnd',
        ),
    ]
