# Generated by Django 2.2.10 on 2021-06-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0009_auto_20210622_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='dateBegin',
            new_name='begin_date',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='dateEnd',
            new_name='end_date',
        ),
    ]
