# Generated by Django 2.2.10 on 2021-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0010_auto_20210622_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='dfsdf',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='name',
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
