# Generated by Django 2.2.10 on 2021-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0011_auto_20210622_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='begin_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='poll',
            name='dfsdf',
            field=models.CharField(default='ff', max_length=10),
        ),
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
