# Generated by Django 2.2.10 on 2021-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0013_auto_20210622_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='name',
        ),
        migrations.AlterField(
            model_name='polls',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
