# Generated by Django 2.2.10 on 2021-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0014_auto_20210622_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='date_begin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='date_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='polls',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='polls',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
