# Generated by Django 2.2.10 on 2021-06-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0015_auto_20210622_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='f_poll',
            new_name='f_polls',
        ),
    ]
