# Generated by Django 2.2.10 on 2021-06-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0016_auto_20210622_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='name',
        ),
    ]
