# Generated by Django 2.2.10 on 2021-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0017_auto_20210622_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
