# Generated by Django 2.2.10 on 2021-06-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0018_polls_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='date_begin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
