# Generated by Django 2.2.10 on 2021-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0019_polls_date_begin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='date_begin',
        ),
        migrations.AddField(
            model_name='polls',
            name='dateBegin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
