# Generated by Django 2.2.10 on 2021-06-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0020_auto_20210622_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='f_polls',
        ),
        migrations.DeleteModel(
            name='Polls',
        ),
    ]
