# Generated by Django 2.2.10 on 2021-06-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0022_auto_20210622_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opros',
            name='date_begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='opros',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
