# Generated by Django 2.2.10 on 2021-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0023_auto_20210622_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
