# Generated by Django 2.2.10 on 2021-06-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0024_useranswers_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswers',
            old_name='count',
            new_name='cnt',
        ),
    ]
