# Generated by Django 2.2.10 on 2021-06-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oprosnik', '0025_auto_20210623_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='cnt',
        ),
    ]
